# Generated by Django 5.1.3 on 2025-06-14 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Comuna",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=100)),
                ("poblacion", models.IntegerField()),
                (
                    "tasa_vulnerabilidad",
                    models.DecimalField(decimal_places=2, max_digits=5),
                ),
                ("fecha_fundacion", models.DateField()),
                ("descripcion", models.TextField(blank=True, null=True)),
            ],
        ),
    ]
